// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	Title string `json:"title"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}
